SELECT NNO, NTITLE, NCONTENT, M.NICK_NAME, NCOUNT, NDATE FROM NOTICE N JOIN MEMBER M ON(N.NWRITER = M.UNO) WHERE N.STATUS='Y' AND NNO=3 ORDER BY NNO DESC;

UPDATE NOTICE SET NCOUNT = (SELECT NCOUNT FROM NOTICE WHERE NNO=?) + 1 WHERE NNO=?;

SELECT * FROM NOTICE;

UPDATE NOTICE SET NTITLE=?, NCONTENT=? WHERE NNO=?;

update NOTICE set STATUS='N' from NOTICE where NNO=?;

SELECT B.BID, B.BTYPE, B.BNO, C.CNAME, B.BTITLE, B.BCONTENT, M.NICK_NAME, B.BCOUNT, B.REF_BID, B.REF_REF_BID, B.REPLY_LEVEL, B.BDATE, B.STATUS FROM BOARD B JOIN MEMBER M ON (B.BWRITER = M.UNO) JOIN CATEGORY C ON (C.CID = B.CID)WHERE B.STATUS = 'Y'AND B.BTYPE = 1AND B.REPLY_LEVEL = 0ORDER BY B.BNO DESC;






insert into BOARD values(SEQ_BID.NEXTVAL, 1, SEQ_BNO1.NEXTVAL, ?, ?, ?, ?, default, NULL, NULL, 0, SYSDATE, default);

select count(*) from BOARD where BTYPE='1';

select * FROM BOARD;

SELECT RNUM, BID, BTYPE, BNO, CNAME, BTITLE, BCONTENT,NICK_NAME, BCOUNT, REF_BID, REF_REF_BID, REPLY_LEVEL, BDATE, STATUS FROM (SELECT ROWNUM RNUM, BID, BTYPE, BNO, CNAME, BTITLE, BCONTENT, NICK_NAME, BCOUNT, REF_BID, REF_REF_BID, REPLY_LEVEL, BDATE, STATUS  FROM (SELECT B.BID, B.BTYPE, B.BNO, C.CNAME, B.BTITLE, B.BCONTENT, M.NICK_NAME, B.BCOUNT, B.REF_BID, B.REF_REF_BID, B.REPLY_LEVEL, B.BDATE, B.STATUS FROM BOARD B JOIN MEMBER M ON(B.BWRITER = M.UNO) JOIN CATEGORY C ON(C.CID = B.CID) WHERE B.STATUS = 'Y' AND B.BTYPE = '1' AND B.REPLY_LEVEL = 0 ORDER BY BID DESC)) WHERE RNUM BETWEEN 1 AND 10;

insert into BOARD values(SEQ_BID.NEXTVAL, 2, SEQ_BNO2.NEXTVAL, NULL, ?, ?, ?, default, null, null, 0, SYSDATE, default);

BID	NUMBER
BTYPE	NUMBER
BNO	NUMBER
CID	NUMBER
BTITLE	VARCHAR2(100 BYTE)
BCOTENT	VARCHAR2(1000 BYTE)
BWRITER	NUMBER
BCOUNT	NUMBER
REF_BID	NUMBER
REF_REF_BID	NUMBER
REPLY_LEVEL	NUMBER
BDATE	DATE
STATUS	VARCHAR2(1 BYTE)

SELECT SEQ_BID.CURRVAL FROM DUAL;  

insert into ATTACHMENT VALUES (SEQ_FID.NEXVAL, ?, ?, ?, ?, SYSDATE, ?, default, default);

SELECT  FROM BOARD;

SELECT B.BID, B.BNO, B.BTITLE, B.BCONTENT, M.NICK_NAME, B.BCOUNT, B.BDATE, A.FID, A.ORIGIN_NAME, A.CHANGE_NAEE, A.FILE_PATH, A.UPLOAD_DATE FROM BOARD B JOIN ATTACHMENT A ON(B.BID=A.BID) JOIN MEMBER M ON (B.BWRITER = M.UNO) WHERE B.STATUS = 'Y' AND A.STATUS = 'Y' AND A.FILE_LEVEL = 0;

SELECT B.BID, B.BNO, B.BTITLE, B.BCONTENT, B.BCONTENT, M.NICK_NAME, B.BCOUNT, B.BDATE, A.FID, A.ORIGIN_NAME, A.CHANGE_NAEE, A.FILE_PATH, A.UPLOAD_DATE FROM BOARD B JOIN ATTACHMENT A ON (B.BID = A.BID) JOIN MEMBER M ON (B.BWRITER = M.UNO) WHERE B.STATUS = 'Y' AND A.STATUS = 'Y' AND A.BID = 65;

SELECT FID, BID, CHANGE_NAEE, FILE_PATH, UPLOAD_DATE, STATUS FROM ATTACHMENT WHERE FID = 65;
